### ISSUE TITLE
`Argument list too long` when I try to use it on 7 889 files

### ISSUE THREAD

**Issue by PetrSnobelt** [lukasoppermann/node-file-rev#1]
Any chance to allow a such number of files to be processed in one batch?
gulp file rev works OK, but I'd like to do not add gulp to a new project.

Thanks

**Comment by lukasoppermann** [comment]
Hey, this should work, can you provide the exact command you are using? Thank you

**Comment by PetrSnobelt** [comment]
`yarn node-file-rev data/scripts/**/*.js`

**Comment by PetrSnobelt** [comment]
for now, I solved it by using `node-file-rev.js` in my script

**Comment by lukasoppermann** [comment]
hey, I am not sure about yarn, but normally you should just run `node-file-rev data/scripts/**/*.js` without the `yarn` keyword before. 

`Argument list too long` does not refer to the amount of files, but to the arguments provided to the script.
